/**
 * RepOS local bootstrap.
 *
 * Creates the local env files if they are missing, and makes sure the SQLite
 * data directory exists. Runs before `dev`, `db:push` and `setup`.
 *
 * Split:
 *   .env        -> DATABASE_URL only. Read by BOTH Next.js and the Prisma CLI.
 *                  Contains no secrets.
 *   .env.local  -> everything else, including API keys. Read by Next.js only.
 *
 * Both files are gitignored.
 */
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const created = [];

const dataDir = resolve(root, 'data');
if (!existsSync(dataDir)) {
  mkdirSync(dataDir, { recursive: true });
  created.push('data/');
}
const uploadsDir = resolve(dataDir, 'uploads');
if (!existsSync(uploadsDir)) {
  mkdirSync(uploadsDir, { recursive: true });
  created.push('data/uploads/');
}

const envPath = resolve(root, '.env');
if (!existsSync(envPath)) {
  writeFileSync(
    envPath,
    [
      '# Auto-generated by scripts/ensure-env.mjs — gitignored.',
      '# Keep this file free of secrets: it exists only so the Prisma CLI can',
      '# find the database. All keys live in .env.local.',
      '#',
      '# M20: RepOS runs on PostgreSQL. There is deliberately no default value',
      '# here any more — a wrong guess used to mean a migration command aimed',
      '# itself at whatever file happened to be at the old relative path.',
      '# Set both explicitly; DIRECT_DATABASE_URL bypasses the pooler so that',
      '# migrations work against Supabase.',
      '# DATABASE_URL="postgresql://user:pass@host:5432/repos?schema=public"',
      '# DIRECT_DATABASE_URL="postgresql://user:pass@host:5432/repos?schema=public"',
      '',
    ].join('\n'),
    'utf8',
  );
  created.push('.env');
}

const envLocalPath = resolve(root, '.env.local');
const examplePath = resolve(root, '.env.example');
if (!existsSync(envLocalPath) && existsSync(examplePath)) {
  writeFileSync(envLocalPath, readFileSync(examplePath, 'utf8'), 'utf8');
  created.push('.env.local');
}

if (created.length > 0) {
  console.log(`[repos] created: ${created.join(', ')}`);
}
